services:
  mysqldb:
    image: mysql:8.0.30
    ports:
      - "5455:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: luxiergerie
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./src/main/resources/import.sql:/docker-entrypoint-initdb.d/import.sql
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - mysqldb
    environment:
      LIQUIBASE_URL: jdbc:mysql://mysqldb:3306/luxiergerie
      LIQUIBASE_CHANGELOG_FILE: /liquibase/changelog/db.changelog-master.xml
      LIQUIBASE_USERNAME: test
      LIQUIBASE_PASSWORD: test
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command: update
    networks:
      - springboot-mysql-network

  luxiergerie-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: bugbstrspro/luxiergerie:dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/luxiergerie
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - '8090:8090'
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - springboot-mysql-network

volumes:
  mysql-data:

networks:
  springboot-mysql-network:
    name: springboot-mysql-network
