name: CI

on:
  push:
    branches:
      - deployCI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_MOHAMED }}
          password: ${{ secrets.DOCKERHUB_TOKEN_MOHAMED }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: final
          tags: ${{ secrets.DOCKERHUB_USERNAME_MOHAMED }}/luxiergerie:deployCI