name: Publish Docker image

on:
  push:
    branches:
      - main
      - dev
      - deployCI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots spring-boot:build-image -Dimage.tag=${GITHUB_REF##*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_MOHAMED }}
          password: ${{ secrets.DOCKERHUB_TOKEN_MOHAMED }}
      - name: Push
        run: |
          docker push mohamedehn/luxiergerie:${GITHUB_REF##*/}